# Generated by Django 2.0.5 on 2020-07-07 13:12

from django.db import migrations, models
import django.db.models.deletion
import wyvern.util.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wyvernsite", "0014_wyvernsite_site_redirect"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernCustomContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wyvern_custom_content_label", models.CharField(max_length=255)),
                (
                    "wyvern_custom_content_content",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "wyvern_custom_content_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wyvern.util.upload.get_file_path,
                    ),
                ),
                (
                    "wyvern_custom_content_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
    ]
