# Generated by Django 3.1 on 2020-09-07 21:52

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernCustomContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvern_custom_content_label', models.CharField(blank=True, max_length=255, null=True)),
                ('wyvern_custom_content_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('wyvern_custom_content_content', models.TextField(blank=True, null=True)),
                ('wyvern_custom_content_image', models.ImageField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
            ],
        ),
    ]
