# Generated by Django 2.0.5 on 2020-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyverncontent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyverncustomcontent",
            name="wyvern_custom_content_slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyverncustomcontent",
            name="wyvern_custom_content_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
