# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyverntheme_name', models.CharField(max_length=255, unique=True)),
                ('wyverntheme_slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernThemeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyverntheme_index_template', models.CharField(blank=True, max_length=255, null=True)),
                ('wyverntheme_base_layout', models.CharField(blank=True, max_length=255, null=True)),
                ('wyverntheme_header_template', models.CharField(blank=True, max_length=255, null=True)),
                ('wyverntheme_footer_template', models.CharField(blank=True, max_length=255, null=True)),
                ('wyverntheme_custom_css', models.TextField(blank=True, null=True)),
                ('wyverntheme_custom_js', models.TextField(blank=True, null=True)),
                ('wyverntheme_google_fonts', models.TextField(blank=True, null=True)),
                ('wyverntheme_back_to_top', models.BooleanField(default=False)),
                ('wyverntheme_gdpr', models.BooleanField(default=False)),
                ('wyverntheme_site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvernsite_theme_site', to='wyvernsite.wyvernsite')),
                ('wyverntheme_theme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvernsite_theme_theme', to='wyvernthemes.wyverntheme')),
            ],
        ),
    ]
