# Generated by Django 2.0.5 on 2020-06-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0006_auto_20200327_2348"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_google_fonts",
            field=models.TextField(blank=True, null=True),
        ),
    ]
