# Generated by Django 2.0.5 on 2020-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0007_wyvernthemeconfig_wyverntheme_google_fonts"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_footer_template",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_header_template",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
