# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernLMSStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvernlms_firstname', models.CharField(max_length=255)),
                ('wyvernlms_middlename', models.CharField(max_length=255)),
                ('wyvernlms_lastname', models.CharField(max_length=255)),
                ('wyvernlms_birthdate', models.DateTimeField(blank=True, null=True)),
                ('wyvernlms_gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Undisclosed')], default='u', max_length=255, null=True)),
                ('wyvernlms_email_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('wyvernlms_mobile_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
