# Generated by Django 2.0.5 on 2020-06-22 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wyvernsite", "0013_auto_20200327_1320"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernLMSStudent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wyvernlms_firstname", models.CharField(max_length=255)),
                ("wyvernlms_middlename", models.CharField(max_length=255)),
                ("wyvernlms_lastname", models.CharField(max_length=255)),
                ("wyvernlms_birthdate", models.DateTimeField(blank=True)),
                (
                    "wyvernlms_gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female"), ("u", "Undisclosed")],
                        default="u",
                        max_length=255,
                    ),
                ),
                (
                    "wyvernlms_email_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "wyvernlms_mobile_number",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "wyvernlms_prev_school",
                    models.CharField(
                        choices=[
                            ("0", "Unspecified"),
                            ("1", "School 1"),
                            ("2", "School 1"),
                        ],
                        default="0",
                        max_length=255,
                    ),
                ),
                (
                    "wyvernlms_year_graduated",
                    models.CharField(
                        choices=[
                            (2020, 2020),
                            (2019, 2019),
                            (2018, 2018),
                            (2017, 2017),
                            (2016, 2016),
                            (2015, 2015),
                            (2014, 2014),
                            (2013, 2013),
                            (2012, 2012),
                            (2011, 2011),
                            (2010, 2010),
                            (2009, 2009),
                        ],
                        default=2020,
                        max_length=255,
                    ),
                ),
                (
                    "wyvernlms_wyvern_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
                (
                    "wyvernlms_wyvern_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
