# Generated by Django 2.0.5 on 2020-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernlms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_year_graduated",
            field=models.CharField(
                blank=True,
                choices=[
                    (2020, 2020),
                    (2019, 2019),
                    (2018, 2018),
                    (2017, 2017),
                    (2016, 2016),
                    (2015, 2015),
                    (2014, 2014),
                    (2013, 2013),
                    (2012, 2012),
                    (2011, 2011),
                    (2010, 2010),
                    (2009, 2009),
                ],
                default=2020,
                max_length=255,
                null=True,
            ),
        ),
    ]
