# Generated by Django 2.0.5 on 2020-06-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernlms", "0002_auto_20200622_2342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female"), ("u", "Undisclosed")],
                default="u",
                max_length=255,
                null=True,
            ),
        ),
    ]
