# Generated by Django 2.0.5 on 2020-06-22 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernlms", "0003_auto_20200622_2343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_wyvern_site",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernsite.WyvernSite",
            ),
        ),
        migrations.AlterField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_wyvern_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_year_graduated",
            field=models.CharField(
                blank=True,
                choices=[
                    ("2020", "2020"),
                    ("2019", "2019"),
                    ("2018", "2018"),
                    ("2017", "2017"),
                    ("2016", "2016"),
                    ("2015", "2015"),
                    ("2014", "2014"),
                    ("2013", "2013"),
                    ("2012", "2012"),
                    ("2011", "2011"),
                    ("2010", "2010"),
                    ("2009", "2009"),
                ],
                default=2020,
                max_length=255,
                null=True,
            ),
        ),
    ]
