# Generated by Django 2.0.5 on 2020-07-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernlms", "0005_auto_20200622_2351"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_prev_school",
        ),
        migrations.RemoveField(
            model_name="wyvernlmsstudent",
            name="wyvernlms_year_graduated",
        ),
    ]
