# Generated by Django 3.1 on 2020-09-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyvernuser', '0002_user_resident_establishment_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=True),
        ),
    ]
