# Generated by Django 3.1.1 on 2020-09-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyvernuser', '0005_auto_20200908_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
