# Generated by Django 2.0.5 on 2020-02-20 02:42

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0003_auto_20200220_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsite",
            name="site_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_google_map",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_logo_dark",
            field=models.ImageField(
                blank=True, null=True, upload_to=wyvern.util.upload.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_number_alt",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
