# Generated by Django 2.0.5 on 2020-03-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0004_auto_20200220_0242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_template",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("aggro", "Aggro"),
                    ("midrange", "Mid Range"),
                    ("taxproblem", "Tax Problem"),
                    ("control", "Control"),
                    ("parallax", "Parallax"),
                    ("debt", "Debt"),
                    ("taxproblem", "Tax Problem"),
                    ("jobscalle", "Jobs Calle Uno"),
                    ("lifeunited", "Life United"),
                    ("medical", "Medical"),
                ],
                default="aggro",
                max_length=50,
            ),
        ),
    ]
