# Generated by Django 2.0.5 on 2020-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0007_auto_20200319_0443"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsite",
            name="site_addthis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_fb_admins",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_google_verification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernsite",
            name="site_recaptcha",
            field=models.TextField(blank=True, null=True),
        ),
    ]
