# Generated by Django 2.0.5 on 2020-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0008_auto_20200324_0722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_addthis",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_fb_admins",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_google_verification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_recaptcha",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
