# Generated by Django 2.0.5 on 2020-03-24 07:26

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0009_auto_20200324_0726"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsite",
            name="site_favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to=wyvern.util.upload.get_file_path
            ),
        ),
    ]
