# Generated by Django 2.0.5 on 2020-03-27 12:45

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0011_auto_20200324_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsite",
            name="site_meta_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wyvern.util.upload.get_file_path
            ),
        ),
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_template",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("parallax", "Parallax"),
                    ("taxproblem", "Tax Problem"),
                    ("jobs", "Jobs"),
                    ("jobscalle", "Jobs Calle Uno"),
                    ("medical", "Medical"),
                    ("techapp", "Tech Company"),
                    ("backlinersph", "Backline PH"),
                ],
                default="aggro",
                max_length=50,
            ),
        ),
    ]
