# Generated by Django 2.0.5 on 2020-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0012_auto_20200327_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernsite",
            name="site_template",
            field=models.CharField(
                choices=[
                    ("basic", "Basic"),
                    ("parallax", "Parallax"),
                    ("taxproblem", "Tax Problem"),
                    ("jobs", "Jobs"),
                    ("jobscalle", "Jobs Calle Uno"),
                    ("medical", "Medical"),
                    ("techapp", "Tech Company"),
                    ("backlinersph", "Backliners PH"),
                ],
                default="aggro",
                max_length=50,
            ),
        ),
    ]
