# Generated by Django 2.0.5 on 2020-07-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0013_auto_20200327_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsite",
            name="site_redirect",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
