# Generated by Django 2.0.5 on 2020-08-09 03:47

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ('wyvernsite', '0014_wyvernsite_site_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyvernsite',
            name='site_favicon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=wyvern.util.upload.get_file_path),
        ),
        migrations.AlterField(
            model_name='wyvernsite',
            name='site_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=wyvern.util.upload.get_file_path),
        ),
        migrations.AlterField(
            model_name='wyvernsite',
            name='site_logo_dark',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=wyvern.util.upload.get_file_path),
        ),
        migrations.AlterField(
            model_name='wyvernsite',
            name='site_meta_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=wyvern.util.upload.get_file_path),
        ),
    ]
