# Generated by Django 2.0.5 on 2020-02-18 05:01

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WyvernPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=255)),
                ("post_slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("page", "Page"),
                            ("job", "Job"),
                            ("custom", "Custom"),
                        ],
                        default="post",
                        max_length=100,
                    ),
                ),
                ("post_content", models.TextField(blank=True, null=True)),
                (
                    "post_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wyvern.util.upload.get_file_path,
                    ),
                ),
                (
                    "post_custom_template",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "post_carousel",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
