# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyvernblog', '0001_initial'),
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyvernpost',
            name='post_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernpost',
            name='post_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
    ]
