# Generated by Django 2.0.5 on 2020-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernblog", "0002_auto_20200218_0501"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernpost",
            name="post_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernpost",
            name="post_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
