# Generated by Django 2.0.5 on 2020-03-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernblog", "0003_auto_20200316_0757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernpost",
            name="post_author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
