# Generated by Django 2.0.5 on 2020-03-24 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernblog", "0004_auto_20200324_0722"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernpost",
            name="post_seo_author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernpost",
            name="post_author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
