# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernDataStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_store_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('data_store_content', models.TextField(blank=True, null=True)),
                ('data_store_tags', models.TextField(blank=True, null=True)),
                ('data_store_timestamp', models.DateTimeField(auto_now_add=True)),
                ('data_store_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
            ],
        ),
    ]
