# Generated by Django 2.0.5 on 2020-04-27 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wyvernsite", "0013_auto_20200327_1320"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernDataStore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_store_identity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_store_content", models.TextField(blank=True, null=True)),
                ("data_store_tags", models.TextField(blank=True, null=True)),
                ("data_store_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "data_store_status",
                    models.IntegerField(choices=[(0, "inactive"), (1, "active")]),
                ),
                (
                    "data_store_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
    ]
