# Generated by Django 2.0.5 on 2020-04-27 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyverndatastorage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyverndatastore",
            name="data_store_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernsite.WyvernSite",
            ),
        ),
    ]
