# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wyverndatastorage', '0001_initial'),
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyverndatastore',
            name='data_store_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
    ]
