# Generated by Django 2.0.5 on 2020-04-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyverndatastorage", "0002_auto_20200427_0541"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyverndatastore",
            name="data_store_status",
            field=models.IntegerField(
                choices=[(0, "inactive"), (1, "active")], default=1
            ),
        ),
    ]
