# Generated by Django 2.0.5 on 2020-03-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wyvernsite", "0004_auto_20200220_0242"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernSubscibers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_firstname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_lastname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_fullname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_status",
                    models.IntegerField(
                        choices=[("0", "inactive"), ("1", "active"), ("2", "suspended")]
                    ),
                ),
                ("sub_date", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
