# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_email', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'suspended')])),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('sub_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite')),
            ],
        ),
    ]
