# Generated by Django 2.0.5 on 2020-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsubscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernsubscibers",
            name="sub_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
