# Generated by Django 2.0.5 on 2020-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsubscriptions", "0002_wyvernsubscibers_sub_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernsubscibers",
            name="sub_status",
            field=models.IntegerField(
                choices=[(0, "inactive"), (1, "active"), (2, "suspended")]
            ),
        ),
    ]
