# Generated by Django 2.0.5 on 2020-03-02 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0004_auto_20200220_0242"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wyvernsubscriptions", "0003_auto_20200302_0752"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WyvernSubscibers",
            new_name="WyvernSubscribers",
        ),
    ]
