# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wyvernshop', '0001_initial'),
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyvernshippingmethod',
            name='shipping_method_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernshippingmethod',
            name='shipping_method_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernshippingtype'),
        ),
    ]
