# Generated by Django 2.0.5 on 2020-02-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wyvernsite", "0001_initial"),
        ("wyvernshop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernshippingmethod",
            name="shipping_method_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernsite.WyvernSite",
            ),
        ),
        migrations.AddField(
            model_name="wyvernshippingmethod",
            name="shipping_method_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernshop.WyvernShippingType",
            ),
        ),
    ]
