# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyvernshop', '0002_auto_20200908_1014'),
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyvernshippingaddress',
            name='shipping_address_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernshippingaddress',
            name='shipping_address_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernproducttypeconfigoption',
            name='product_type_config_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproducttypeconfig'),
        ),
        migrations.AddField(
            model_name='wyvernproducttypeconfig',
            name='product_type_config_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproducttype'),
        ),
        migrations.AddField(
            model_name='wyvernproducttype',
            name='product_type_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernproductconfig',
            name='product_config_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproducttypeconfig'),
        ),
        migrations.AddField(
            model_name='wyvernproductconfig',
            name='product_config_option_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproducttypeconfigoption'),
        ),
        migrations.AddField(
            model_name='wyvernproductcategory',
            name='product_category_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernproductcategory',
            name='product_parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproductcategory'),
        ),
        migrations.AddField(
            model_name='wyvernproductcategories',
            name='product_categories_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproductcategory'),
        ),
        migrations.AddField(
            model_name='wyvernproductcategories',
            name='product_categories_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproduct'),
        ),
        migrations.AddField(
            model_name='wyvernproduct',
            name='product_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernproduct',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproducttype'),
        ),
        migrations.AddField(
            model_name='wyvernpaymentmethod',
            name='payment_method_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernpayment',
            name='payment_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernpaymentmethod'),
        ),
        migrations.AddField(
            model_name='wyvernpayment',
            name='payment_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernorder'),
        ),
        migrations.AddField(
            model_name='wyvernpayment',
            name='payment_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernorderproducts',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproduct'),
        ),
        migrations.AddField(
            model_name='wyvernorder',
            name='order_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernshippingaddress'),
        ),
        migrations.AddField(
            model_name='wyvernorder',
            name='order_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyverncart'),
        ),
        migrations.AddField(
            model_name='wyvernorder',
            name='order_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernorder',
            name='order_payment_method',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernpaymentmethod'),
        ),
        migrations.AddField(
            model_name='wyvernorder',
            name='order_shipping_method',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernshippingmethod'),
        ),
        migrations.AddField(
            model_name='wyverninventory',
            name='inventory_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproduct'),
        ),
        migrations.AddField(
            model_name='wyverninventory',
            name='inventory_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyverncartitem',
            name='cart_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyverncart'),
        ),
        migrations.AddField(
            model_name='wyverncartitem',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernshop.wyvernproduct'),
        ),
        migrations.AddField(
            model_name='wyverncart',
            name='cart_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyverncart',
            name='cart_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
    ]
