# Generated by Django 3.1 on 2020-09-02 01:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernTraceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvern_first_name', models.CharField(default='My first name', max_length=255)),
                ('wyvern_last_name', models.CharField(default='My last name', max_length=255)),
                ('wyvern_phone_number', models.CharField(default='0000000000', max_length=13)),
                ('wyvern_email_address', models.CharField(default='name@name.com', max_length=255)),
                ('wyvern_temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('wyvern_trace_date', models.DateTimeField(auto_now_add=True)),
                ('wyvern_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to=settings.AUTH_USER_MODEL)),
                ('wyvern_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernMedicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvern_medical_form_date', models.DateField(default=datetime.date.today)),
                ('wyvern_have_sore_throat', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_body_pain', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_head_ache', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_fever', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_near_covid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_contact_symptoms', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_travelled_outside_philippines', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_travelled_ncr', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_medical_form_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvern_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
