# Generated by Django 3.1 on 2020-09-07 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernMedicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvern_medical_form_date', models.DateField(default=datetime.date.today)),
                ('wyvern_have_sore_throat', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_body_pain', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_head_ache', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_have_fever', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_near_covid', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_contact_symptoms', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_travelled_outside_philippines', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('wyvern_travelled_ncr', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernTraceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyvern_temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('wyvern_trace_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
