# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyverntrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyverntracelog',
            name='wyvern_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyverntracelog',
            name='wyvern_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_medical_form_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvern_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
