# Generated by Django 3.1 on 2020-09-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyverntrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyverntracelog',
            name='wyvern_resident_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wyverntracelog',
            name='wyvern_email_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wyverntracelog',
            name='wyvern_first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wyverntracelog',
            name='wyvern_last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wyverntracelog',
            name='wyvern_phone_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
