# Generated by Django 3.1 on 2020-09-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyverntrace', '0002_auto_20200904_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wyverntracelog',
            name='wyvern_email_address',
        ),
    ]
