# Generated by Django 3.1 on 2020-08-26 09:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyverntrace', '0002_wyvernmedicalform'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_contact_symptoms',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_have_body_pain',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_have_fever',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_have_head_ache',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_have_sore_throat',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_medical_form_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_medical_form_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvern_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_near_covid',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_travelled_ncr',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='wyvernmedicalform',
            name='wyvern_travelled_outside_philippines',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
