# Generated by Django 3.1 on 2020-09-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyverntrace', '0003_auto_20200826_1703'),
        ('wyverntrace', '0003_auto_20200901_0522'),
    ]

    operations = [
    ]
