# Generated by Django 3.1 on 2020-09-07 21:52

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WyvernEmployer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_employer_title', models.TextField(blank=True, null=True)),
                ('job_employer_company_name', models.TextField(blank=True, null=True)),
                ('job_employer_company_image', models.ImageField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernEmployerJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WyvernJobApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_applicant_firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('job_applicant_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('job_applicant_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_applicant_email', models.CharField(blank=True, max_length=255, null=True)),
                ('job_applicant_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_applicant_resume', models.FileField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
                ('job_applicant_additional_form', models.FileField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernJobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_application_cover_letter', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernJobCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category_title', models.CharField(max_length=255)),
                ('job_category_description', models.TextField(blank=True, null=True)),
                ('job_category_short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category_image', models.ImageField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
                ('job_category_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')])),
                ('job_category_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('job_slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('job_image', models.ImageField(blank=True, null=True, upload_to=wyvern.util.upload.get_file_path)),
                ('job_status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')])),
                ('job_experience_required', models.CharField(default='Entry Level', max_length=255)),
                ('job_content', models.TextField(blank=True, null=True)),
                ('job_location', models.CharField(default='Baguio City', max_length=255)),
                ('job_hours', models.CharField(choices=[('Temporary', 'Temporary'), ('Agency Staffing', 'Agency Staffing'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Part Time / Full Time', 'Part Time / Full Time'), ('Project Based', 'Project Based')], default='Full Time', max_length=100)),
                ('job_type', models.CharField(choices=[('general', 'General'), ('it', 'Information Technology and Service'), ('hr', 'Human Resources'), ('cs', 'Customer Support'), ('va', 'Virtual Assistance'), ('ck', 'Cleaning / Kitchen'), ('hca', 'Health Care Assistant'), ('nurse', 'Nurse'), ('sw', 'Support Workers'), ('marketing', 'Marketing and Advertising')], default='general', max_length=100)),
                ('job_notifications_recipients', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WyvernJobTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type_title', models.CharField(max_length=255)),
            ],
        ),
    ]
