# Generated by Django 2.0.5 on 2020-02-18 05:01

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WyvernJobs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField(blank=True, null=True)),
                (
                    "job_subtitle",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wyvern.util.upload.get_file_path,
                    ),
                ),
                (
                    "job_status",
                    models.IntegerField(choices=[(0, "inactive"), (1, "active")]),
                ),
                ("job_content", models.TextField(blank=True, null=True)),
                (
                    "job_notifications_recipients",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
