# Generated by Django 2.0.5 on 2020-02-18 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wyvernjobs", "0001_initial"),
        ("wyvernsite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobs",
            name="job_posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wyvernjobs",
            name="job_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wyvernsite.WyvernSite"
            ),
        ),
    ]
