# Generated by Django 3.1.1 on 2020-09-08 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyvernjobs', '0002_wyvernjobtypes_job_type_site'),
        ('wyvernsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyvernjobs',
            name='job_posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernjobs',
            name='job_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernjobcategories',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernjobcategories',
            name='job_category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernjobs.wyvernjobcategories'),
        ),
        migrations.AddField(
            model_name='wyvernjobcategories',
            name='job_category_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernjobapplication',
            name='job_application_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyvernjobs.wyvernjobapplicant'),
        ),
        migrations.AddField(
            model_name='wyvernjobapplication',
            name='job_application_applicant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernjobapplication',
            name='job_application_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernjobs.wyvernjobs'),
        ),
        migrations.AddField(
            model_name='wyvernjobapplication',
            name='job_application_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernjobapplicant',
            name='job_applicant_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernjobapplicant',
            name='job_applicant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wyvernuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wyvernemployerjobs',
            name='job_employer_jobs_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernjobs.wyvernemployer'),
        ),
        migrations.AddField(
            model_name='wyvernemployerjobs',
            name='job_employer_jobs_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernjobs.wyvernjobs'),
        ),
        migrations.AddField(
            model_name='wyvernemployerjobs',
            name='job_employer_jobs_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernemployer',
            name='job_employer_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wyvernsite.wyvernsite'),
        ),
        migrations.AddField(
            model_name='wyvernemployer',
            name='job_employer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
