# Generated by Django 2.0.5 on 2020-03-13 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernsite", "0005_auto_20200310_0206"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wyvernjobs", "0003_wyvernjobs_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernJobApplicant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_application_applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_application_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernjobs.WyvernJobs",
                    ),
                ),
                (
                    "job_application_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WyvernJobCategories",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_category_title", models.CharField(max_length=255)),
                ("job_category_description", models.TextField(blank=True, null=True)),
                (
                    "job_category_short_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_category_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_category_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wyvern.util.upload.get_file_path,
                    ),
                ),
                (
                    "job_category_status",
                    models.IntegerField(choices=[(0, "inactive"), (1, "active")]),
                ),
                ("job_category_content", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_category_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernjobs.WyvernJobCategories",
                    ),
                ),
                (
                    "job_category_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WyvernJobTypes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type_title", models.CharField(max_length=255)),
                (
                    "job_type_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
    ]
