# Generated by Django 2.0.5 on 2020-03-13 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wyvernsite", "0005_auto_20200310_0206"),
        ("wyvernjobs", "0004_wyvernjobapplicant_wyvernjobcategories_wyvernjobtypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernEmployer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_employer_title", models.TextField(blank=True, null=True)),
                ("job_employer_company_name", models.TextField(blank=True, null=True)),
                (
                    "job_employer_company_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=wyvern.util.upload.get_file_path,
                    ),
                ),
                (
                    "job_employer_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
                (
                    "job_employer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WyvernEmployerJobs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_employer_jobs_employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernjobs.WyvernEmployer",
                    ),
                ),
                (
                    "job_employer_jobs_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernjobs.WyvernJobs",
                    ),
                ),
                (
                    "job_employer_jobs_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WyvernJobApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_application_applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_application_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernjobs.WyvernJobs",
                    ),
                ),
                (
                    "job_application_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wyvernsite.WyvernSite",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="wyvernjobapplicant",
            old_name="job_application_site",
            new_name="job_applicant_site",
        ),
        migrations.RenameField(
            model_name="wyvernjobapplicant",
            old_name="job_application_applicant",
            new_name="job_applicant_user",
        ),
        migrations.RemoveField(
            model_name="wyvernjobapplicant", name="job_application_job",
        ),
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
