# Generated by Django 2.0.5 on 2020-03-23 06:18

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0005_auto_20200313_0331"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_resume",
            field=models.FileField(
                blank=True, null=True, upload_to=wyvern.util.upload.get_file_path
            ),
        ),
        migrations.AddField(
            model_name="wyvernjobapplication",
            name="job_application_cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
