# Generated by Django 2.0.5 on 2020-03-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0006_auto_20200323_0618"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobapplicant",
            name="job_applicant_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
