# Generated by Django 2.0.5 on 2020-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0007_auto_20200323_0627"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
