# Generated by Django 2.0.5 on 2020-03-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0008_auto_20200323_0819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobapplicant",
            name="job_applicant_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
