# Generated by Django 2.0.5 on 2020-03-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0011_wyvernjobapplication_job_application_applicant_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wyvernjobapplication", name="job_application_applicant_info",
        ),
    ]
