# Generated by Django 2.0.5 on 2020-03-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wyvernjobs",
            "0012_remove_wyvernjobapplication_job_application_applicant_info",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobs",
            name="job_location",
            field=models.CharField(default="Baguio City", max_length=50),
        ),
    ]
