# Generated by Django 2.0.5 on 2020-03-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0014_wyvernjobs_job_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_frequency",
            field=models.CharField(
                choices=[("Part Time", "Part Time"), ("Full Time", "Full Time")],
                default="Full Time",
                max_length=50,
            ),
        ),
    ]
