# Generated by Django 2.0.5 on 2020-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0015_auto_20200324_1535"),
    ]

    operations = [
        migrations.RemoveField(model_name="wyvernjobs", name="job_frequency",),
        migrations.AddField(
            model_name="wyvernjobs",
            name="job_hours",
            field=models.CharField(
                choices=[
                    ("Part Time", "Part Time"),
                    ("Full Time", "Full Time"),
                    ("Project Based", "Project Based"),
                ],
                default="Full Time",
                max_length=50,
            ),
        ),
    ]
