# Generated by Django 2.0.5 on 2020-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0016_auto_20200324_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobs",
            name="job_experience_required",
            field=models.CharField(default="Entry Level", max_length=255),
        ),
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_location",
            field=models.CharField(default="Baguio City", max_length=255),
        ),
    ]
