# Generated by Django 2.0.5 on 2020-06-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0017_auto_20200325_0144"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_hours",
            field=models.CharField(
                choices=[
                    ("Temporary", "Temporary"),
                    ("Agency Staffing", "Agency Staffing"),
                    ("Part Time", "Part Time"),
                    ("Full Time", "Full Time"),
                    ("Project Based", "Project Based"),
                ],
                default="Full Time",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("it", "Information Technology and Service"),
                    ("hr", "Human Resources"),
                    ("cs", "Customer Support"),
                    ("va", "Virtual Assistance"),
                    ("ck", "Cleaning / Kitchen"),
                    ("hca", "Health care Assistant"),
                    ("nurse", "Nurse"),
                    ("sw", "Support Workers"),
                    ("marketing", "Marketing and Advertising"),
                ],
                default="general",
                max_length=50,
            ),
        ),
    ]
