# Generated by Django 2.0.5 on 2020-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0019_auto_20200603_0241"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_hours",
            field=models.CharField(
                choices=[
                    ("Temporary", "Temporary"),
                    ("Agency Staffing", "Agency Staffing"),
                    ("Part Time", "Part Time"),
                    ("Full Time", "Full Time"),
                    ("Part Time / Full Time", "Part Time / Full Time"),
                    ("Project Based", "Project Based"),
                ],
                default="Full Time",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("it", "Information Technology and Service"),
                    ("hr", "Human Resources"),
                    ("cs", "Customer Support"),
                    ("va", "Virtual Assistance"),
                    ("ck", "Cleaning / Kitchen"),
                    ("hca", "Health Care Assistant"),
                    ("nurse", "Nurse"),
                    ("sw", "Support Workers"),
                    ("marketing", "Marketing and Advertising"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
