# Generated by Django 2.0.5 on 2020-06-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0021_auto_20200605_0006"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_firstname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_lastname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernjobapplication",
            name="job_application_applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
