# Generated by Django 2.0.5 on 2020-06-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0023_auto_20200610_0956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobapplication",
            name="job_application_applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernjobs.WyvernJobApplicant",
            ),
        ),
    ]
