# Generated by Django 2.0.5 on 2020-06-10 11:43

from django.db import migrations, models
import wyvern.util.upload


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0025_wyvernjobapplication_job_application_applicant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernjobapplicant",
            name="job_applicant_additional_form",
            field=models.FileField(
                blank=True, null=True, upload_to=wyvern.util.upload.get_file_path
            ),
        ),
    ]
