# Generated by Django 2.0.5 on 2020-06-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0026_wyvernjobapplicant_job_applicant_additional_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wyvernjobapplicant", name="job_applicant_introduction",
        ),
    ]
