# Generated by Django 2.0.5 on 2020-06-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernjobs", "0027_remove_wyvernjobapplicant_job_applicant_introduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernjobs",
            name="job_slug",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
