# Generated by Django 2.0.5 on 2020-08-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyvernjobs', '0018_auto_20200511_0535'),
        ('wyvernjobs', '0028_auto_20200622_0027'),
    ]

    operations = [
    ]
