# Generated by Django 2.0.5 on 2020-03-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wyvernsite", "0011_auto_20200324_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="WyvernTheme",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wyverntheme_name", models.CharField(max_length=255, unique=True)),
                ("wyverntheme_slug", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WyvernThemeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wyverntheme_index_template",
                    models.CharField(max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WyvernThemeSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wyverntheme_site_site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wyvern_site",
                        to="wyvernsite.WyvernSite",
                    ),
                ),
                (
                    "wyverntheme_site_theme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wyvern_site_theme",
                        to="wyvernthemes.WyvernTheme",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="wyvernthemes.WyvernThemeSite",
            ),
        ),
    ]
