# Generated by Django 2.0.5 on 2020-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_custom_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_custom_js",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_index_template",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
