# Generated by Django 2.0.5 on 2020-03-27 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0002_auto_20200327_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wyvernsite.WyvernSite"
            ),
        ),
    ]
