# Generated by Django 2.0.5 on 2020-06-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0008_auto_20200601_0349"),
    ]

    operations = [
        migrations.AddField(
            model_name="wyvernthemeconfig",
            name="wyverntheme_page_layout",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
