# Generated by Django 2.0.5 on 2020-06-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wyvernthemes", "0009_wyvernthemeconfig_wyverntheme_page_layout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wyvernthemeconfig",
            old_name="wyverntheme_page_layout",
            new_name="wyverntheme_base_layout",
        ),
    ]
